module.exports = {
  ADD_MODEL_TO_SCENE: "ADD_MODEL_TO_SCENE",
  REMOVE_MODEL_FROM_SCENE: "REMOVE_MODEL_FROM_SCENE",
  LOAD_JSON_MODEL: "LOAD_JSON_MODEL",

  MODEL_LOADED: "MODEL_LOADED",
  ITEM_START_LOAD: "ITEM_START_LOAD",
  ITEM_LOADED: "ITEM_LOADED",
  ALL_ITEMS_LOADED: "ALL_ITEMS_LOADED",
  RESET_RAYCASTER: "RESET_RAYCASTER",

  UNSET_ALL_HOVER_MODELS: "UNSET_ALL_HOVER_MODELS",
  SET_CAMERA_POSITION: "SET_CAMERA_POSITION",

  TIMELINE_MANAGER_UPDATE: "TIMELINE_MANAGER_UPDATE",

  ANIMATE_CAMERA: "ANIMATE_CAMERA",
  SELECT_SCENE_MODELS: "SELECT_SCENE_MODELS",

  INVADE_COUNTRY: "INVADE_COUNTRY",
  NEXT_TIMELINE_MODEL: "NEXT_TIMELINE_MODEL",

  TIMELINE_MODEL_ANIMATION_COMPLETE: "TIMELINE_MODEL_ANIMATION_COMPLETE",
  CHANGE_COUNTRY_POWER: "CHANGE_COUNTRY_POWER",
  UPDATE_SCENE_MODELS: "UPDATE_SCENE_MODELS",
  CAMERA_ANIMATION_COMPLETE: "CAMERA_ANIMATION_COMPLETE"

};
