module.exports = {
  ON_RESIZE: "ON_RESIZE",
  HOVER_NAVIGATION: "HOVER_NAVIGATION",
  HOVER_ALL_AXIS_OR_ALLY: "HOVER_ALL_AXIS_OR_ALLY",
  LOAD_TIMELINE_MODEL: "LOAD_TIMELINE_MODEL",
  START_TIMELINE_MODEL: "START_TIMELINE_MODEL"
};
