module.exports = {
  ON_RESIZE: "ON_RESIZE",
  HOVER_NAVIGATION: "HOVER_NAVIGATION",
  HOVER_ALL_AXIS_OR_ALLY: "HOVER_ALL_AXIS_OR_ALLY",
  UPDATE_TIMELINE_MODEL_TEXT: "UPDATE_TIMELINE_MODEL_TEXT",
  START_TIMELINE_MODEL: "START_TIMELINE_MODEL",
  TIMELINE_MANAGER_END: "TIMELINE_MANAGER_END"
};
