module.exports = {
  PARSE_JSON_MODEL: "PARSE_JSON_MODEL",
  GET_TEXT_MESH: "GET_TEXT_MESH",
  GET_SCENE_MODEL: "GET_SCENE_MODEL",
  GET_SCENE_MODELS: "GET_SCENE_MODELS",
  TEST_OFFSCREEN: "TEST_OFFSCREEN",
  GET_COUNTRY_MESH: "GET_COUNTRY_MESH",
  GET_CURVE: "GET_CURVE"
};
